### ISSUE TITLE
Question regarding `Free` joints export

### ISSUE THREAD

**Issue by bchretien** [jorisv/RBDynUrdf#2]
Why isn't it possible to export `Free` joints as `floating` URDF joints (cf. [URDF joint types](https://github.com/ros/urdfdom_headers/blob/master/urdf_model/include/urdf_model/joint.h#L173-L176) and [their descriptions](http://wiki.ros.org/urdf/XML/joint))?

**Comment by jorisv** [comment]
I was not aware of the existence of the floating joint in the urdf.
In which version of ROS this joint has been added ?
Anyway I will look at your pull request and merge it.
